import './globals.css'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

const myFont = localFont({
  src: '../fonts/R_Bold.ttf',
  display: 'swap',
  // variable: '--font-RBold'
})

export const metadata: Metadata = {
  title: 'AWTS',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={myFont.className}>
      <body>{children}</body>
    </html>
  )
}
